// Lookup Codes

export const LookupTypes = {
  CUSTOMER_TYPE: 'CUSTOMER_TYPE',
  COMPANY_OWNER: 'COMPANY_OWNER',
  TEAM_MANAGER: 'TEAM_MANAGER',
  TEAM_MEMBER: 'TEAM_MEMBER',
  INDUSTRY_PROJECT: 'INDUSTRY_PROJECT',
  TASK_ROLE: 'TASK_ROLE',
  TODO_LIST: 'TODO_LIST',
  ALERT_MODE: 'ALERT_MODE',
  CLIENT_FEEDBACK: 'CLIENT_FEEDBACK',
  DOCUMENT_FILE: 'DOCUMENT_FILE',
  GOOGLE_MEET: 'GOOGLE_MEET',
  EVENT_PROGRAMS: 'EVENT_PROGRAMS',
  RECRUITMENT_POST: 'RECRUITMENT_POST',
};
