// Lookup Codes

export const LookupTypes = {
  CUSTOMER_TYPE: 'CUSTOMER_TYPE',
  COMPANY_OWNER: 'COMPANY_OWNER',
  TEAM_MANAGER: 'TEAM_MANAGER',
  TEAM_MEMBER: 'TEAM_MEMBER',
  INDUSTRY_PROJECT: 'INDUSTRY_PROJECT',
  TASK_ROLE: 'TASK_ROLE',
};
